apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}
    namespace: petclinic
spec:
    ports:
    - name: api-gateway
      targetPort: 8080
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: api-gateway
    type: {{ .Values.service.type }}