apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: petclinic
spec:
    ports:
    - name: visits-service
      targetPort: 8082
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: visits-service
    type: {{ .Values.service.type }}