apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: petclinic
  labels:
    app: tracing-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}"
        ports:
        - containerPort: 9411
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M
