apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  namespace: petclinic
spec:
  ingressClassName: traefik
  tls:
  - secretName: petclinic-secret
    hosts:
      - capstone.formation-datascientest.cloudns.ph
  rules:
  - host: capstone.formation-datascientest.cloudns.ph
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: discovery-server-svc
              port:
                number: 31685
        - path: /config-server
          pathType: Prefix
          backend:
             service:
              name: config-server-svc
              port:
                number: 31567
        - path: /tracing-server
          pathType: Prefix
          backend:
             service:
              name: tracing-server-svc
              port:
                number: 32193
        - path: /grafana-server
          pathType: Prefix
          backend:
             service:
              name: grafana-server-svc
              port:
                number: 32380                
        - path: /prometheus-server
          pathType: Prefix
          backend:
             service:
              name: prometheus-server-svc
              port:
                number: 30098
        - path: /api-gateway
          pathType: Prefix
          backend:
             service:
              name: api-gateway-svc
              port:
                number: 32433 
        - path: /admin-server
          pathType: Prefix
          backend:
             service:
              name: admin-server-svc
              port:
                number: 32401   
        - path: /vets-service
          pathType: Prefix
          backend:
             service:
              name: vets-service-svc
              port:
                number: 32764   
        - path: /visits-service
          pathType: Prefix
          backend:
             service:
              name: visits-service-svc
              port:
                number: 30243     
        - path: /customers-server
          pathType: Prefix
          backend:
             service:
              name: customers-server-svc
              port:
                number: 31834                                                                 