apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: discovery.petclinic.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: discovery-server
              port:
                number: 8761
                                                                                                                                                       