apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: petclinic
  labels:
    app: config-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}"
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M